### ISSUE TITLE
Unable to package due to editor only module

### ISSUE THREAD

**Issue by Crezetique** [Nebukam/PCGExtendedToolkit#17]
Hello there, first off I want to preface that I do apologies if I'm misunderstanding the uses of the plugin. I have limited C++ knowledge and an avid blueprint abuser. I've mainly been using the plugin to generate spline with pathfinding at runtime using blueprints.

---

I'm running into an issue where the UE5.3 would fail to package the game. Looking into the log and some googling, I found that PCGExtendedToolkit introduces the UnrealEd module which is editor only and cannot be packaged.

```
Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
(referenced via Target -> PCGExtendedToolkit.Build.cs)
BuildException: Unable to instantiate UnrealEd module for non-editor targets.
```

I did some sanity tests — removing the plugin solves the issue and it can be replicated in a fresh project.

<details>
  <summary>Click here for full logs</summary>
  
  ### :(
```Log started at 02/02/2024 00:55:24 (2024-02-01T16:55:24Z)
No config file at C:\Users\creze\OneDrive\Documents\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml
Configuration will be read from:
  C:\Users\creze\AppData\Roaming\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml
Log file: C:\Users\creze\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+Epic+Games+UE_5.3\UBT-testproj-Win64-Shipping.txt

Setting temp directory to 'C:\Users\creze\AppData\Local\Temp\UnrealBuildTool\e6b63909'
    Registering build platform: UnrealBuildTool.AndroidPlatformFactory
    Registering build platform: UnrealBuildTool.IOSPlatformFactory
    Registering build platform: UnrealBuildTool.LinuxPlatformFactory
        Registering build platform: Linux - buildable: False
        Registering build platform: LinuxArm64 - buildable: False
    Registering build platform: UnrealBuildTool.MacPlatformFactory
    Registering build platform: UnrealBuildTool.TVOSPlatformFactory
    Registering build platform: UnrealBuildTool.WindowsPlatformFactory
Found Windows 10 SDK root at C:\Program Files (x86)\Windows Kits\10 (1)
Found Windows 10 SDK root at C:\Program Files (x86)\Windows Kits\10 (2)
Found Windows 10 SDK version 10.0.18362.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.18362.0 at C:\Program Files (x86)\Windows Kits\10
Found Windows 10 SDK version 10.0.19041.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.19041.0 at C:\Program Files (x86)\Windows Kits\10
Found Windows 10 SDK version 10.0.20348.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.20348.0 at C:\Program Files (x86)\Windows Kits\10
Found Windows 10 SDK version 10.0.22000.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.22000.0 at C:\Program Files (x86)\Windows Kits\10
Found Windows 10 SDK version 10.0.22621.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.22621.0 at C:\Program Files (x86)\Windows Kits\10
Win64 Installed SDK(s): MinVersion_Sdk=10.0.00000.0, MaxVersion_Sdk=10.9.99999.0, CurrentVersion_Sdk=10.0.18362.0, Version_AutoSdk=10.0.18362.0, CurrentVersion_AutoSdk=
        Registering build platform: Win64 - buildable: True
Command line: "D:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" testproj Win64 Shipping "-Project=C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\testproj.uproject" "-Manifest=C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Intermediate\Build\Manifest.xml" "-remoteini=C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj" -skipdeploy "-log=C:\Users\creze\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+Epic+Games+UE_5.3\UBT-testproj-Win64-Shipping.txt"
Using 'git status' to determine working set for adaptive non-unity build (C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj).
Makefile is older than UnrealBuildTool assembly, ignoring it
Creating makefile for testproj (UnrealBuildTool assembly is newer)
Skipping D:\Program Files\Epic Games\UE_5.3\Engine\Intermediate\Build\BuildRules\UE5Rules.dll: File is installed
Skipping D:\Program Files\Epic Games\UE_5.3\Engine\Intermediate\Build\BuildRules\UE5ProgramRules.dll: File is installed
Found Visual Studio installation: C:\Program Files\Microsoft Visual Studio\2022\Community (Product=Microsoft.VisualStudio.Product.Community, Version=17.8.34322.80)
Found Visual Studio installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools (Product=Microsoft.VisualStudio.Product.BuildTools, Version=16.11.34301.259)
Found Visual Studio installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community (Product=Microsoft.VisualStudio.Product.Community, Version=16.11.34301.259)
Found Visual Studio toolchain: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130 (Family=14.38.33130, FamilyRank=4, Version=14.38.33130, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64, Error=False, Redist=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.38.33130)
Building UnrealGame - testproj - Win64 - Shipping
Total execution time: 0.58 seconds
Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
(referenced via Target -> PCGExtendedToolkit.Build.cs)
BuildException: Unable to instantiate UnrealEd module for non-editor targets.
   at UnrealEd..ctor(ReadOnlyTargetRules Target) in D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\UnrealEd.Build.cs:line 12Wrapped by TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 542Wrapped by BuildException: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
(referenced via Target -> PCGExtendedToolkit.Build.cs)
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 561
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 423
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 423
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 423
   at UnrealBuildTool.UEBuildTarget.CreateModuleRulesAndSetDefaults(String ModuleName, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 5210
   at UnrealBuildTool.UEBuildTarget.FindOrCreateModuleByName(String ModuleName, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 5334
   at UnrealBuildTool.UEBuildTarget.<>c__DisplayClass66_0.<PreBuildSetup>b__0(String Name, String RefChain) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3335
   at UnrealBuildTool.UEBuildModule.RecursivelyCreateModulesByName(List`1 ModuleNames, List`1& Modules, Boolean& bDependsOnVerse, CreateModuleDelegate CreateModule, String ReferenceChain, List`1 ReferenceStack, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildModule.cs:line 1230
   at UnrealBuildTool.UEBuildModule.RecursivelyCreateModules(CreateModuleDelegate CreateModule, String ReferenceChain, List`1 ReferenceStack, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildModule.cs:line 1178
   at UnrealBuildTool.UEBuildBinary.CreateAllDependentModules(CreateModuleDelegate CreateModule, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildBinary.cs:line 157
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3333
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1366
   at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 1114
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 396
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
WriteFileIfChanged() wrote 0 changed files of 0 requested writes.
Timeline:

[ 0.000]
[ 0.000](+0.597) <unknown>
[ 0.597]
```
</details>

**Comment by Nebukam** [comment]
Hello!
I'll be looking into this today, some nodes are indeed using Editor-only features and I've probably missed a flag to remove it from packaged builds somewhere.

**Comment by Crezetique** [comment]
Much appreciated! 😊

**Comment by Nebukam** [comment]
Howdy again @Crezetique!
I pushed a rather simple fix on the main branch, let me know if it fixes your packaging issue!

I basically removed the `UnrealEd` from public dependency and added this to the `Build.cs`  which hopefully will be enough:

```csharp
// Include "UnrealEd" only for editor configuration
if (Target.bBuildEditor)
{
	PrivateDependencyModuleNames.Add("UnrealEd");
}
```

Side note: "using the plugin to generate spline with pathfinding at runtime using blueprints." is very much what this plugin was designed for :D

**Comment by Crezetique** [comment]
Hey @Nebukam! 

I just attempted to rebuild and package and its still failing. However, looking at the log and diff checking, it looks like its screaming at a different module.

![image](https://github.com/Nebukam/PCGExtendedToolkit/assets/4138125/b0e80070-2d2f-4bad-8c35-19e3c5c361f6)

<details>
  <summary>Click here for full logs</summary>
  
```
Log started at 02/02/2024 03:08:19 (2024-02-01T19:08:19Z)
No config file at C:\Users\creze\OneDrive\Documents\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml
Configuration will be read from:
  C:\Users\creze\AppData\Roaming\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml
Log file: C:\Users\creze\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+Epic+Games+UE_5.3\UBT-testproj-Win64-Shipping.txt

Setting temp directory to 'C:\Users\creze\AppData\Local\Temp\UnrealBuildTool\e6b63909'
    Registering build platform: UnrealBuildTool.AndroidPlatformFactory
    Registering build platform: UnrealBuildTool.IOSPlatformFactory
    Registering build platform: UnrealBuildTool.LinuxPlatformFactory
        Registering build platform: Linux - buildable: False
        Registering build platform: LinuxArm64 - buildable: False
    Registering build platform: UnrealBuildTool.MacPlatformFactory
    Registering build platform: UnrealBuildTool.TVOSPlatformFactory
    Registering build platform: UnrealBuildTool.WindowsPlatformFactory
Found Windows 10 SDK root at C:\Program Files (x86)\Windows Kits\10 (1)
Found Windows 10 SDK root at C:\Program Files (x86)\Windows Kits\10 (2)
Found Windows 10 SDK version 10.0.18362.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.18362.0 at C:\Program Files (x86)\Windows Kits\10
Found Windows 10 SDK version 10.0.19041.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.19041.0 at C:\Program Files (x86)\Windows Kits\10
Found Windows 10 SDK version 10.0.20348.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.20348.0 at C:\Program Files (x86)\Windows Kits\10
Found Windows 10 SDK version 10.0.22000.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.22000.0 at C:\Program Files (x86)\Windows Kits\10
Found Windows 10 SDK version 10.0.22621.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.22621.0 at C:\Program Files (x86)\Windows Kits\10
Win64 Installed SDK(s): MinVersion_Sdk=10.0.00000.0, MaxVersion_Sdk=10.9.99999.0, CurrentVersion_Sdk=10.0.18362.0, Version_AutoSdk=10.0.18362.0, CurrentVersion_AutoSdk=
        Registering build platform: Win64 - buildable: True
Command line: "D:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" testproj Win64 Shipping "-Project=C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\testproj.uproject" "-Manifest=C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Intermediate\Build\Manifest.xml" "-remoteini=C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj" -skipdeploy "-log=C:\Users\creze\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+Epic+Games+UE_5.3\UBT-testproj-Win64-Shipping.txt"
Using 'git status' to determine working set for adaptive non-unity build (C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj).
Makefile is older than UnrealBuildTool assembly, ignoring it
Creating makefile for testproj (UnrealBuildTool assembly is newer)
Skipping D:\Program Files\Epic Games\UE_5.3\Engine\Intermediate\Build\BuildRules\UE5Rules.dll: File is installed
Skipping D:\Program Files\Epic Games\UE_5.3\Engine\Intermediate\Build\BuildRules\UE5ProgramRules.dll: File is installed
Found Visual Studio installation: C:\Program Files\Microsoft Visual Studio\2022\Community (Product=Microsoft.VisualStudio.Product.Community, Version=17.8.34322.80)
Found Visual Studio installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools (Product=Microsoft.VisualStudio.Product.BuildTools, Version=16.11.34301.259)
Found Visual Studio installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community (Product=Microsoft.VisualStudio.Product.Community, Version=16.11.34301.259)
Found Visual Studio toolchain: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130 (Family=14.38.33130, FamilyRank=4, Version=14.38.33130, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64, Error=False, Redist=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.38.33130)
Building UnrealGame - testproj - Win64 - Shipping
Total execution time: 0.71 seconds
Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
(referenced via Target -> PCGExtendedToolkit.Build.cs -> DetailCustomizations.Build.cs)
BuildException: Unable to instantiate UnrealEd module for non-editor targets.
   at UnrealEd..ctor(ReadOnlyTargetRules Target) in D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\UnrealEd.Build.cs:line 12Wrapped by TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 542Wrapped by BuildException: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
(referenced via Target -> PCGExtendedToolkit.Build.cs -> DetailCustomizations.Build.cs)
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 561
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 423
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 423
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 423
   at UnrealBuildTool.UEBuildTarget.CreateModuleRulesAndSetDefaults(String ModuleName, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 5210
   at UnrealBuildTool.UEBuildTarget.FindOrCreateModuleByName(String ModuleName, String ReferenceChain, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 5334
   at UnrealBuildTool.UEBuildTarget.<>c__DisplayClass66_0.<PreBuildSetup>b__0(String Name, String RefChain) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3335
   at UnrealBuildTool.UEBuildModule.RecursivelyCreateModulesByName(List`1 ModuleNames, List`1& Modules, Boolean& bDependsOnVerse, CreateModuleDelegate CreateModule, String ReferenceChain, List`1 ReferenceStack, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildModule.cs:line 1230
   at UnrealBuildTool.UEBuildModule.RecursivelyCreateModules(CreateModuleDelegate CreateModule, String ReferenceChain, List`1 ReferenceStack, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildModule.cs:line 1184
   at UnrealBuildTool.UEBuildModule.RecursivelyCreateModulesByName(List`1 ModuleNames, List`1& Modules, Boolean& bDependsOnVerse, CreateModuleDelegate CreateModule, String ReferenceChain, List`1 ReferenceStack, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildModule.cs:line 1233
   at UnrealBuildTool.UEBuildModule.RecursivelyCreateModules(CreateModuleDelegate CreateModule, String ReferenceChain, List`1 ReferenceStack, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildModule.cs:line 1184
   at UnrealBuildTool.UEBuildBinary.CreateAllDependentModules(CreateModuleDelegate CreateModule, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildBinary.cs:line 157
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3333
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1366
   at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 1114
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 396
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
WriteFileIfChanged() wrote 0 changed files of 0 requested writes.
Timeline:

[ 0.000]
[ 0.000](+0.736) <unknown>
[ 0.736]
```
</details>


Glad to know I'm using the plugin as intended, it has been such a delight using the plugin :))

**Comment by Nebukam** [comment]
Hah I missed some other modules that I didn't knew were Editor only -- detail customization is actually trying to import UnrealEd as well.
Hopefully the last push fixes it for good -- sorry for the back'n forth >.<

**Comment by Crezetique** [comment]
Not to worry at all, I'm glad that I'm able to somewhat assist :D

I'm running into a completely new error. Looks like a bunch of syntax errors?

<details>
  <summary>Click here for full logs</summary>
```
------ Building 7 action(s) started ------
[1/7] Compile [x64] Module.PCGExtendedToolkit.1.cpp
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\PCGExPointsProcessor.h(291): error C3668: 'FPCGExPointsProcessorElementBase::ShouldLog': method with override specifier 'override' did not override any base class methods
[2/7] Compile [x64] Module.PCGExtendedToolkit.2.cpp
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\PCGExPointsProcessor.h(291): error C3668: 'FPCGExPointsProcessorElementBase::ShouldLog': method with override specifier 'override' did not override any base class methods
[3/7] Compile [x64] Module.PCGExtendedToolkit.3.cpp
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\PCGExPointsProcessor.h(291): error C3668: 'FPCGExPointsProcessorElementBase::ShouldLog': method with override specifier 'override' did not override any base class methods
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(93): error C2143: syntax error: missing ';' before '*'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(93): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(93): error C2238: unexpected token(s) preceding ';'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(116): error C2143: syntax error: missing ';' before '*'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(116): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(116): error C2238: unexpected token(s) preceding ';'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Intermediate\Build\Win64\UnrealGame\Inc\PCGExtendedToolkit\UHT\PCGExPathfindingNavmesh.gen.cpp(241): error C2039: 'NavData': is not a member of 'UPCGExPathfindingNavmeshSettings'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(20): note: see declaration of 'UPCGExPathfindingNavmeshSettings'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Intermediate\Build\Win64\UnrealGame\Inc\PCGExtendedToolkit\UHT\PCGExPathfindingNavmesh.gen.cpp(241): error C2618: illegal member designator in offsetof
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Intermediate\Build\Win64\UnrealGame\Inc\PCGExtendedToolkit\UHT\PCGExPathfindingNavmesh.gen.cpp(241): note: offsetof has a builtin meaning; use /Zc:offsetof- to revert to old, non-conforming definition
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Intermediate\Build\Win64\UnrealGame\Inc\PCGExtendedToolkit\UHT\PCGExPathfindingNavmesh.gen.cpp(241): error C2737: 'NewProp_NavData': const object must be initialized
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingPlotNavmesh.h(89): error C2143: syntax error: missing ';' before '*'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingPlotNavmesh.h(89): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingPlotNavmesh.h(89): error C2238: unexpected token(s) preceding ';'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingPlotNavmesh.h(108): error C2143: syntax error: missing ';' before '*'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingPlotNavmesh.h(108): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingPlotNavmesh.h(108): error C2238: unexpected token(s) preceding ';'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Intermediate\Build\Win64\UnrealGame\Inc\PCGExtendedToolkit\UHT\PCGExPathfindingPlotNavmesh.gen.cpp(241): error C2039: 'NavData': is not a member of 'UPCGExPathfindingPlotNavmeshSettings'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingPlotNavmesh.h(17): note: see declaration of 'UPCGExPathfindingPlotNavmeshSettings'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Intermediate\Build\Win64\UnrealGame\Inc\PCGExtendedToolkit\UHT\PCGExPathfindingPlotNavmesh.gen.cpp(241): error C2618: illegal member designator in offsetof
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Intermediate\Build\Win64\UnrealGame\Inc\PCGExtendedToolkit\UHT\PCGExPathfindingPlotNavmesh.gen.cpp(241): note: offsetof has a builtin meaning; use /Zc:offsetof- to revert to old, non-conforming definition
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Intermediate\Build\Win64\UnrealGame\Inc\PCGExtendedToolkit\UHT\PCGExPathfindingPlotNavmesh.gen.cpp(241): error C2737: 'NewProp_NavData': const object must be initialized
[4/7] Compile [x64] Module.PCGExtendedToolkit.4.cpp
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\PCGExPointsProcessor.h(291): error C3668: 'FPCGExPointsProcessorElementBase::ShouldLog': method with override specifier 'override' did not override any base class methods
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Edges\PCGExDrawEdges.cpp(115): error C2065: 'Context': undeclared identifier
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(93): error C2143: syntax error: missing ';' before '*'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(93): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(93): error C2238: unexpected token(s) preceding ';'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(116): error C2143: syntax error: missing ';' before '*'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(116): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(116): error C2238: unexpected token(s) preceding ';'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(98): error C2039: 'NavData': is not a member of 'UPCGExPathfindingNavmeshSettings'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(20): note: see declaration of 'UPCGExPathfindingNavmeshSettings'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(103): error C2039: 'NavData': is not a member of 'FPCGExPathfindingNavmeshContext'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(97): note: see declaration of 'FPCGExPathfindingNavmeshContext'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(113): error C2039: 'NavData': is not a member of 'FPCGExPathfindingNavmeshContext'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(97): note: see declaration of 'FPCGExPathfindingNavmeshContext'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(190): error C2039: 'NavData': is not a member of 'FPCGExPathfindingNavmeshContext'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\Pathfinding\PCGExPathfindingNavmesh.h(97): note: see declaration of 'FPCGExPathfindingNavmeshContext'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(189): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'FPathFindingQuery'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(189): note: 'FPathFindingQuery::FPathFindingQuery': no overloaded function could convert all the argument types
D:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\NavigationSystem\Public\NavigationSystemTypes.h(57): note: could be 'FPathFindingQuery::FPathFindingQuery(const INavAgentInterface &,const ANavigationData &,const FVector &,const FVector &,FSharedConstNavQueryFilter,FNavPathSharedPtr,const double,const bool)'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(189): note: 'FPathFindingQuery::FPathFindingQuery(const INavAgentInterface &,const ANavigationData &,const FVector &,const FVector &,FSharedConstNavQueryFilter,FNavPathSharedPtr,const double,const bool)': cannot convert argument 1 from 'UWorld *' to 'const INavAgentInterface &'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(190): note: Reason: cannot convert from 'UWorld *' to 'const INavAgentInterface'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(190): note: 'INavAgentInterface::INavAgentInterface': no overloaded function could convert all the argument types
D:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Engine\Classes\AI\Navigation\NavAgentInterface.h(73): note: could be 'INavAgentInterface::INavAgentInterface(const INavAgentInterface &)'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(190): note: 'INavAgentInterface::INavAgentInterface(const INavAgentInterface &)': cannot convert argument 1 from 'UWorld *' to 'const INavAgentInterface &'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(190): note: Reason: cannot convert from 'UWorld *' to 'const INavAgentInterface'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(190): note: Conversion requires a second user-defined-conversion operator or constructor
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(190): note: while trying to match the argument list '(UWorld *)'
D:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\NavigationSystem\Public\NavigationSystemTypes.h(56): note: or       'FPathFindingQuery::FPathFindingQuery(const UObject *,const ANavigationData &,const FVector &,const FVector &,FSharedConstNavQueryFilter,FNavPathSharedPtr,const double,const bool)'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(189): note: 'FPathFindingQuery::FPathFindingQuery(const UObject *,const ANavigationData &,const FVector &,const FVector &,FSharedConstNavQueryFilter,FNavPathSharedPtr,const double,const bool)': cannot convert argument 2 from 'FVector' to 'const ANavigationData &'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(191): note: Reason: cannot convert from 'FVector' to 'const ANavigationData'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(191): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\Pathfinding\PCGExPathfindingNavmesh.cpp(189): note: while trying to match the argument list '(UWorld *, FVector, FVector, nullptr, nullptr, TNumericLimits<double>::NumericType, bool)'
[5/7] Compile [x64] Module.PCGExtendedToolkit.5.cpp
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\PCGExPointsProcessor.h(291): error C3668: 'FPCGExPointsProcessorElementBase::ShouldLog': method with override specifier 'override' did not override any base class methods
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\PCGExConsolidateCustomGraph.cpp(95): error C3861: 'GetFixedIndex': identifier not found
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\PCGExConsolidateCustomGraph.cpp(131): error C2039: 'GetFixedIndex': is not a member of 'FPCGExConsolidateCustomGraphElement'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Public\Graph\PCGExConsolidateCustomGraph.h(56): note: see declaration of 'FPCGExConsolidateCustomGraphElement'
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\PCGExDrawCustomGraph.cpp(16): error C2065: 'DebugSettings': undeclared identifier
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Graph\PCGExDrawCustomGraph.cpp(202): error C2065: 'Context': undeclared identifier
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Misc\PCGExDrawAttributes.cpp(296): error C2065: 'Context': undeclared identifier
C:\Users\creze\OneDrive\Documents\Unreal Projects\testproj\Plugins\PCGExtendedToolkit\Source\PCGExtendedToolkit\Private\Misc\PCGExFlushDebug.cpp(85): error C2065: 'Context': undeclared identifier
Total time in Parallel executor: 1.77 seconds
Total execution time: 2.61 seconds
CompilationResultException: Error: OtherCompilationError
   at UnrealBuildTool.ActionGraph.ExecuteActionsAsync(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute, List`1 TargetDescriptors, ILogger Logger, IActionArtifactCache actionArtifactCache) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 417
   at UnrealBuildTool.BuildMode.BuildAsync(TargetMakefile[] Makefiles, List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 801
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 411
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
WriteFileIfChanged() wrote 0 changed files of 70 requested writes.
Timeline:

[ 0.000]
[ 0.000](+2.626) <unknown>
[ 2.626]
```
</details>

**Comment by Nebukam** [comment]
Ok I'm going to try and build locally instead of doing bite-sized fixes ahah, I assumed it was a quick fix ^^
(still is, I just underestimated the side effects)

**Comment by Nebukam** [comment]
Ok it should be fixed now.
Trying to compile locally revealed a cascade of issue mostly due to private NavigationSystem classes being exposed as UPROPERTY + some other hit-and-miss with the EDITOR_ONLY flag.

I was able to package a dummy project, let me know it finally works for you!
*Also if it doesn't on first try, make sure to remove Binary/Intermediate folders in the both the plugin and project to make sure there's no remaining artifact from the buggy version.*

**Comment by Crezetique** [comment]
Hey @Nebukam! I can confirm that there are no longer any issues with packaging. Thank you so much for the help 🥹❤️

**Comment by Nebukam** [comment]
Aaah that's nice to read :D
Thanks a lot for logging the issue in the first place <3
